version: "3.9"

services:
  db:
    image: mysql:lts
    container_name: fragote_tech
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: fragote_db
    ports:
      - "3306:3306"
    volumes:
      - ./mysqldata:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "8080:80"
